/**
 * Studio session identity, connection state, and realm tracking.
 */

/**
 * Which DataModel a plugin connection is attached to.
 *
 * Studio does not keep one stable DataModel across a playtest. Starting "Run"
 * keeps a server DataModel with no player; starting "Play" produces a client
 * DataModel where LocalPlayer and PlayerGui exist. The plugin reports which one
 * it is in so an agent never mistakes a missing LocalPlayer for a bug.
 * Spec sections 13 and 15.
 */
export type StudioRealm = "edit" | "server" | "client" | "unknown";

export type PlaytestMode = "play" | "run";

export interface RunState {
  /** True when the place is running (either Run or Play). */
  running: boolean;
  /** True while Studio is in edit mode. */
  edit: boolean;
  /** Best-effort classification of how the session was started. */
  mode: PlaytestMode | null;
  realm: StudioRealm;
  /**
   * Increments on every edit/run transition. Handles are stamped with the epoch
   * they were created in, so a runtime handle can never be replayed against an
   * edit-time instance. Spec section 30.
   */
  epoch: number;
  /** True once a LocalPlayer and character exist, where applicable. */
  ready: boolean;
}

export const EDIT_RUN_STATE: RunState = {
  running: false,
  edit: true,
  mode: null,
  realm: "edit",
  epoch: 0,
  ready: false,
};

export interface PlaceInfo {
  placeId: number;
  gameId: number;
  /** Place name as shown in Studio, or the file name for unpublished places. */
  name: string;
  /** True when the place has never been saved or published. */
  unsaved: boolean;
}

export type ConnectionStatus = "disconnected" | "pairing" | "connected" | "stale";

/**
 * One plugin connection. A single Studio window can have more than one at a
 * time during a playtest, so commands are routed to an endpoint rather than to
 * a session.
 */
export interface StudioEndpoint {
  id: string;
  realm: StudioRealm;
  run: RunState;
  /** Epoch milliseconds of the last successful sync. */
  lastSeen: number;
  /** True when a sync request is currently parked, waiting for commands. */
  polling: boolean;
}

export interface StudioSession {
  /** Stable id for this Studio window, persisted across reconnects. */
  id: string;
  /** Random per-install id generated by the plugin, used to re-issue tokens. */
  installId: string;
  place: PlaceInfo;
  studioVersion: string;
  pluginVersion: string;
  status: ConnectionStatus;
  /** Live plugin connections, ordered most recently seen first. */
  endpoints: StudioEndpoint[];
  /** Run state of the endpoint commands are currently routed to. */
  run: RunState;
  lastSeen: number;
  /** True when this session receives commands from the harness and MCP. */
  active: boolean;
}

export interface PairingRequest {
  sessionId: string;
  installId: string;
  code: string;
  place: PlaceInfo;
  studioVersion: string;
  pluginVersion: string;
  requestedAt: number;
  expiresAt: number;
}

export interface SessionStatus {
  serverVersion: string;
  /** All Studio sessions the server currently knows about. */
  sessions: StudioSession[];
  /** Id of the session commands are routed to, if any. */
  activeSessionId: string | null;
  /** Pairing requests waiting for user approval. */
  pending: PairingRequest[];
}

/**
 * Deterministic endpoint selection.
 *
 * Preferring the most recent connection would flap between two long-polling
 * plugin instances, so realm order decides instead: during a playtest the
 * client DataModel is where GUI, camera, and input live, and it is what an
 * agent almost always wants to observe.
 */
export function selectEndpoint(session: StudioSession, preferred?: StudioRealm): StudioEndpoint | null {
  if (session.endpoints.length === 0) return null;
  if (preferred) {
    return session.endpoints.find((endpoint) => endpoint.realm === preferred) ?? null;
  }

  const order: StudioRealm[] = session.run.running ? ["client", "server", "unknown", "edit"] : ["edit", "server", "client", "unknown"];
  for (const realm of order) {
    const match = session.endpoints.find((endpoint) => endpoint.realm === realm);
    if (match) return match;
  }
  return session.endpoints[0] ?? null;
}
